export default {
    tags: new Set(['kolesa', 'all']),
    src: "pics/products/kolesa/kolesaBG.jpeg", //пикчи запихнуть
    name: "Колесные опоры большегрузные",
    html:"<div class=\"btp-detail-desc\">\n" +
        "\t\t\t<div class=\"btp-detail-desc-full\">\n" +
        "\t\t\t\t<div>\n" +
        "\t\t\t\t<p>Большегрузные колеса, чугунный обод, шинка – черная резина, в оси колеса роликовый подшипник, платформенное крепление под четыре болта. Сварные кронштейны.<br>Диаметр колес: 100 – 250 мм. Нагрузка: до 350 кг.</p>\n" +
        "<p>&nbsp;</p>\n" +
        "<p>Большегрузные колеса поворотные:</p>\n" +
        "<table border=\"0\" style=\"width: 544px; border-collapse: collapse; height: 168px;\" cellspacing=\"0\" cellpadding=\"0\">\n" +
        "<tbody>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"width: 59pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-color: windowtext; border-width: 1pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">Наименование</span></td>\n" +
        "<td style=\"width: 41pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><img src=\"/images/IMG/01.jpg\" alt=\"01\" width=\"54\" height=\"82\"></td>\n" +
        "<td style=\"width: 42pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 21pt;\" width=\"56\">&nbsp;<img src=\"/images/IMG/02.jpg\" alt=\"02\" width=\"50\" height=\"77\"></td>\n" +
        "<td style=\"width: 46pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 21pt;\" width=\"61\">&nbsp;<img src=\"/images/IMG/00008.jpg\" alt=\"00008\" width=\"73\" height=\"77\"></td>\n" +
        "<td style=\"width: 50pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"67\">&nbsp;<img src=\"/images/IMG/00006.jpg\" alt=\"00006\" width=\"83\" height=\"80\"></td>\n" +
        "<td style=\"width: 41.25pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\">&nbsp;<img src=\"/images/IMG/00007.jpg\" alt=\"00007\" width=\"80\" height=\"79\"></td>\n" +
        "<td style=\"width: 36.25pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"48\">&nbsp;<img src=\"/images/IMG/05.jpg\" alt=\"05\" width=\"49\" height=\"84\"></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"width: 59pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">SCD 42</span></td>\n" +
        "<td style=\"width: 41pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">100</span></td>\n" +
        "<td style=\"width: 42pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" width=\"56\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"width: 46pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" width=\"61\"><span style=\"font-size: 10pt;\">135</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">115x100</span></td>\n" +
        "<td style=\"width: 41.25pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">85x73</span></td>\n" +
        "<td style=\"width: 36.25pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"48\"><span style=\"font-size: 10pt;\">130</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"width: 59pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">SCD 55</span></td>\n" +
        "<td style=\"width: 41pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">125</span></td>\n" +
        "<td style=\"width: 42pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" width=\"56\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"width: 46pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" width=\"61\"><span style=\"font-size: 10pt;\">159</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">115x100</span></td>\n" +
        "<td style=\"width: 41.25pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">85x73</span></td>\n" +
        "<td style=\"width: 36.25pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"48\"><span style=\"font-size: 10pt;\">160</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"width: 59pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">SCD 63</span></td>\n" +
        "<td style=\"width: 41pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">150</span></td>\n" +
        "<td style=\"width: 42pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" width=\"56\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"width: 46pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" width=\"61\"><span style=\"font-size: 10pt;\">189</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">115x100</span></td>\n" +
        "<td style=\"width: 41.25pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">85x73</span></td>\n" +
        "<td style=\"width: 36.25pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"48\"><span style=\"font-size: 10pt;\">230</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"width: 59pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">SCD 80</span></td>\n" +
        "<td style=\"width: 41pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">200</span></td>\n" +
        "<td style=\"width: 42pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" width=\"56\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"width: 46pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" width=\"61\"><span style=\"font-size: 10pt;\">235</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">115x100</span></td>\n" +
        "<td style=\"width: 41.25pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">85x73</span></td>\n" +
        "<td style=\"width: 36.25pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"48\"><span style=\"font-size: 10pt;\">280</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"width: 59pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">SCD 85</span></td>\n" +
        "<td style=\"width: 41pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">250</span></td>\n" +
        "<td style=\"width: 42pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" width=\"56\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"width: 46pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" width=\"61\"><span style=\"font-size: 10pt;\">294</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">115х100</span></td>\n" +
        "<td style=\"width: 41.25pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">85х73</span></td>\n" +
        "<td style=\"width: 36.25pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 21pt; text-align: center;\" nowrap=\"nowrap\" width=\"48\"><span style=\"font-size: 10pt;\">350</span></td>\n" +
        "</tr>\n" +
        "</tbody>\n" +
        "</table>\n" +
        "<p>&nbsp;</p>\n" +
        "<p>&nbsp;&nbsp;Большегрузные колеса неповоротные:</p>\n" +
        "<table border=\"0\" style=\"border-collapse: collapse; width: 544px; height: 168px;\" cellspacing=\"0\" cellpadding=\"0\">\n" +
        "<tbody>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"border-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-color: windowtext; width: 59pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">Наименование</span></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 41pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><img src=\"/images/IMG/01.jpg\" alt=\"01\" width=\"54\" height=\"82\"></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 42pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"56\">&nbsp;<img src=\"/images/IMG/02.jpg\" alt=\"02\" width=\"50\" height=\"77\"></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 46pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"61\">&nbsp;<img src=\"/images/IMG/00008.jpg\" alt=\"00008\" width=\"73\" height=\"77\"></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"67\">&nbsp;<img src=\"/images/IMG/00006.jpg\" alt=\"00006\" width=\"83\" height=\"80\"></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\">&nbsp;<img src=\"/images/IMG/00007.jpg\" alt=\"00007\" width=\"80\" height=\"79\"></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"48\">&nbsp;<img src=\"/images/IMG/05.jpg\" alt=\"05\" width=\"49\" height=\"84\"></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 59pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">FCD 46</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">100</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 42pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"56\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 46pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"61\"><span style=\"font-size: 10pt;\">135</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">115x100</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">85x73</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"48\"><span style=\"font-size: 10pt;\">130</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 59pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">FCD 54</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">125</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 42pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"56\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 46pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"61\"><span style=\"font-size: 10pt;\">159</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">115x100</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">85x73</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"48\"><span style=\"font-size: 10pt;\">160</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 59pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">FCD 63</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">150</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 42pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"56\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 46pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"61\"><span style=\"font-size: 10pt;\">189</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">115x100</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">85x73</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"48\"><span style=\"font-size: 10pt;\">230</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 59pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">FCD 80</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">200</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 42pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"56\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 46pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"61\"><span style=\"font-size: 10pt;\">235</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">115x100</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">85x73</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"48\"><span style=\"font-size: 10pt;\">280</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 21pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 59pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"79\"><span style=\"font-size: 10pt;\">FCD 85</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">250</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 42pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"56\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 46pt; padding: 0cm 5.4pt; height: 21pt;\" width=\"61\"><span style=\"font-size: 10pt;\">294</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">115х100</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">85х73</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.25pt; padding: 0cm 5.4pt; height: 21pt;\" nowrap=\"nowrap\" width=\"48\"><span style=\"font-size: 10pt;\">350</span></td>\n" +
        "</tr>\n" +
        "</tbody>\n" +
        "</table>\t\t\t\t</div>\n" +
        "\t\t\t</div>\n" +
        "\t\t\t<div class=\"btp-detail-extrafields\">\n" +
        "\t\t\t\t\t\t\t</div>\n" +
        "\t\t</div>"
}