export default {
    tags: new Set(['kolesa', 'all']),
    src: "pics/products/kolesa/promkolesa.jpeg", //пикчи запихнуть
    name: "Колесные опоры промышленные",
    html: "<div class=\"btp-detail-desc\">\n" +
        "\t\t\t<div class=\"btp-detail-desc-full\">\n" +
        "\t\t\t\t<div>\n" +
        "\t\t\t\t<p>Колеса транспортные,&nbsp;стальной обод состоящий из двух половинок, скрепленных пятью заклепками. Шинка - стандартная литая резина черного цвета, в оси колеса роликовый (игольчатый) подшипник. Поставляются в комплекте с двумя стальными колпачками, втулкой, болтом и гайкой. Рабочая температура от -25°С до +50°С.</p>\n" +
        "<p>&nbsp;</p>\n" +
        "<p>Колеса поворотные:</p>\n" +
        "<table border=\"0\" style=\"width: 599px; border-collapse: collapse; height: 147px;\" cellspacing=\"0\" cellpadding=\"0\">\n" +
        "<tbody>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"width: 73.3pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-color: windowtext; border-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">Наименование</span></td>\n" +
        "<td style=\"width: 37.15pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"50\">&nbsp;<img src=\"/pics/01.jpg\" alt=\"01\" width=\"52\" height=\"78\"></td>\n" +
        "<td style=\"width: 36.65pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"49\">&nbsp;<img src=\"/pics/02.jpg\" alt=\"02\" width=\"46\" height=\"71\"></td>\n" +
        "<td style=\"width: 40.9pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"55\">&nbsp;<img src=\"/pics/00008.jpg\" alt=\"00008\" width=\"78\" height=\"83\"></td>\n" +
        "<td style=\"width: 50pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"67\">&nbsp;<img src=\"/pics/00006.jpg\" alt=\"00006\" width=\"84\" height=\"82\"></td>\n" +
        "<td style=\"width: 41.5pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"55\">&nbsp;<img src=\"/pics/00007.jpg\" alt=\"00007\" width=\"80\" height=\"79\"></td>\n" +
        "<td style=\"width: 35.75pt; border-right-style: solid; border-bottom-style: solid; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-left-style: none; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"48\">&nbsp;<img src=\"/pics/05.jpg\" alt=\"05\" width=\"48\" height=\"82\"></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"width: 73.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">SC 93</span></td>\n" +
        "<td style=\"width: 37.15pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"50\"><span style=\"font-size: 10pt;\">75</span></td>\n" +
        "<td style=\"width: 36.65pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"49\"><span style=\"font-size: 10pt;\">23</span></td>\n" +
        "<td style=\"width: 40.9pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"55\"><span style=\"font-size: 10pt;\">97</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">84X72</span></td>\n" +
        "<td style=\"width: 41.5pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">50X62</span></td>\n" +
        "<td style=\"width: 35.75pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"48\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"width: 73.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">SC 42</span></td>\n" +
        "<td style=\"width: 37.15pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"50\"><span style=\"font-size: 10pt;\">100</span></td>\n" +
        "<td style=\"width: 36.65pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"49\"><span style=\"font-size: 10pt;\">27</span></td>\n" +
        "<td style=\"width: 40.9pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"55\"><span style=\"font-size: 10pt;\">130</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">84x102</span></td>\n" +
        "<td style=\"width: 41.5pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">60x80</span></td>\n" +
        "<td style=\"width: 35.75pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"48\"><span style=\"font-size: 10pt;\">70</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"width: 73.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">SC 55</span></td>\n" +
        "<td style=\"width: 37.15pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"50\"><span style=\"font-size: 10pt;\">125</span></td>\n" +
        "<td style=\"width: 36.65pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"49\"><span style=\"font-size: 10pt;\">34</span></td>\n" +
        "<td style=\"width: 40.9pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"55\"><span style=\"font-size: 10pt;\">155</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">84x102</span></td>\n" +
        "<td style=\"width: 41.5pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">60x80</span></td>\n" +
        "<td style=\"width: 35.75pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"48\"><span style=\"font-size: 10pt;\">100</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"width: 73.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">SC 63</span></td>\n" +
        "<td style=\"width: 37.15pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"50\"><span style=\"font-size: 10pt;\">160</span></td>\n" +
        "<td style=\"width: 36.65pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"49\"><span style=\"font-size: 10pt;\">40</span></td>\n" +
        "<td style=\"width: 40.9pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"55\"><span style=\"font-size: 10pt;\">195</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">105x135</span></td>\n" +
        "<td style=\"width: 41.5pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">75x105</span></td>\n" +
        "<td style=\"width: 35.75pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"48\"><span style=\"font-size: 10pt;\">145</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"width: 73.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">SC 80</span></td>\n" +
        "<td style=\"width: 37.15pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"50\"><span style=\"font-size: 10pt;\">200</span></td>\n" +
        "<td style=\"width: 36.65pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"49\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"width: 40.9pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"55\"><span style=\"font-size: 10pt;\">235</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">105x135</span></td>\n" +
        "<td style=\"width: 41.5pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">75x105</span></td>\n" +
        "<td style=\"width: 35.75pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"48\"><span style=\"font-size: 10pt;\">185</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"width: 73.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">SC 85</span></td>\n" +
        "<td style=\"width: 37.15pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"50\"><span style=\"font-size: 10pt;\">250</span></td>\n" +
        "<td style=\"width: 36.65pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"49\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"width: 40.9pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"55\"><span style=\"font-size: 10pt;\">285</span></td>\n" +
        "<td style=\"width: 50pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">105x135</span></td>\n" +
        "<td style=\"width: 41.5pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">75x105</span></td>\n" +
        "<td style=\"width: 35.75pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 15.75pt; text-align: center;\" width=\"48\"><span style=\"font-size: 10pt;\">210</span></td>\n" +
        "</tr>\n" +
        "</tbody>\n" +
        "</table>\n" +
        "<p>&nbsp;</p>\n" +
        "<p>&nbsp;Колеса неповоротные:</p>\n" +
        "<table border=\"0\" style=\"border-collapse: collapse; width: 599px; height: 147px;\" cellspacing=\"0\" cellpadding=\"0\">\n" +
        "<tbody>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"border-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-color: windowtext; width: 73.3pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">Наименование</span></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 37.15pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"50\">&nbsp;<img src=\"/pics/01.jpg\" alt=\"01\" width=\"52\" height=\"78\"></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.65pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"49\">&nbsp;<img src=\"/pics/02.jpg\" alt=\"02\" width=\"46\" height=\"71\"></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 40.9pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"55\">&nbsp;<img src=\"/pics/00008.jpg\" alt=\"00008\" width=\"78\" height=\"83\"></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"67\">&nbsp;<img src=\"/pics/00006.jpg\" alt=\"00006\" width=\"84\" height=\"82\"></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.5pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"55\">&nbsp;<img src=\"/pics/00007.jpg\" alt=\"00007\" width=\"80\" height=\"79\"></td>\n" +
        "<td style=\"border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-right-style: solid; border-bottom-style: solid; border-left-style: none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; width: 35.75pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"48\">&nbsp;<img src=\"/pics/05.jpg\" alt=\"05\" width=\"48\" height=\"82\"></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 73.3pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">FC 93</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 37.15pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"50\"><span style=\"font-size: 10pt;\">75</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.65pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"49\"><span style=\"font-size: 10pt;\">23</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 40.9pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"55\"><span style=\"font-size: 10pt;\">97</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">84X72</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.5pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">50X62</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 35.75pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"48\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 73.3pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">FC 46</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 37.15pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"50\"><span style=\"font-size: 10pt;\">100</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.65pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"49\"><span style=\"font-size: 10pt;\">27</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 40.9pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"55\"><span style=\"font-size: 10pt;\">130</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">84x102</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.5pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">60x80</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 35.75pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"48\"><span style=\"font-size: 10pt;\">70</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 73.3pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">FC 54</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 37.15pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"50\"><span style=\"font-size: 10pt;\">125</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.65pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"49\"><span style=\"font-size: 10pt;\">34</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 40.9pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"55\"><span style=\"font-size: 10pt;\">155</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">84x102</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.5pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">60x80</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 35.75pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"48\"><span style=\"font-size: 10pt;\">100</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 73.3pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">FC 63</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 37.15pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"50\"><span style=\"font-size: 10pt;\">160</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.65pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"49\"><span style=\"font-size: 10pt;\">40</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 40.9pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"55\"><span style=\"font-size: 10pt;\">195</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">105x135</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.5pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">75x105</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 35.75pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"48\"><span style=\"font-size: 10pt;\">145</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 73.3pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">FC 80</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 37.15pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"50\"><span style=\"font-size: 10pt;\">200</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.65pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"49\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 40.9pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"55\"><span style=\"font-size: 10pt;\">235</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">105x135</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.5pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">75x105</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 35.75pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"48\"><span style=\"font-size: 10pt;\">185</span></td>\n" +
        "</tr>\n" +
        "<tr style=\"height: 15.75pt;\">\n" +
        "<td style=\"border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; width: 73.3pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"98\"><span style=\"font-size: 10pt;\">FC 85</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 37.15pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"50\"><span style=\"font-size: 10pt;\">250</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 36.65pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"49\"><span style=\"font-size: 10pt;\">50</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 40.9pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"55\"><span style=\"font-size: 10pt;\">285</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 50pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"67\"><span style=\"font-size: 10pt;\">105x135</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 41.5pt; padding: 0cm 5.4pt; height: 15.75pt;\" nowrap=\"nowrap\" width=\"55\"><span style=\"font-size: 10pt;\">75x105</span></td>\n" +
        "<td style=\"text-align: center; border-right-width: 1pt; border-bottom-width: 1pt; border-style: none solid solid none; border-right-color: windowtext; border-bottom-color: windowtext; width: 35.75pt; padding: 0cm 5.4pt; height: 15.75pt;\" width=\"48\"><span style=\"font-size: 10pt;\">210</span></td>\n" +
        "</tr>\n" +
        "</tbody>\n" +
        "</table>\t\t\t\t</div>\n" +
        "\t\t\t</div>\n" +
        "\t\t\t<div class=\"btp-detail-extrafields\">\n" +
        "\t\t\t\t\t\t\t</div>\n" +
        "\t\t</div>",
}