export default{
    tags: new Set(['telega', 'all']),
    src: "pics/products/telega/samoxod.jpeg", //пикчи запихнуть
    name: "САМОХОДНЫЕ ТЕЛЕЖКИ",
    html:"<div class=\"btp-detail-desc\">\n" +
        "\t\t\t<div class=\"btp-detail-desc-full\">\n" +
        "\t\t\t\t<div>\n" +
        "\t\t\t\t<table border=\"0\" style=\"cursor: default; border: 1px dashed #bbbbbb; border-spacing: 1px; font-family: Verdana, Arial, Helvetica, sans-serif; height: 231px; width: 994px;\">\n" +
        "<tbody>\n" +
        "<tr>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>Модель</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>Г/п, кг</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>Высота подъема вил, мм</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>Ширина вил, мм</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>Длина вил, мм</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>Размер прохода с поддоном, мм</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>Вес, кг</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>Аккумулятор</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>Высота в сложенном состоянии, мм</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>Скорость передвижения (с грузом/без груза) км/ч</strong></span></td>\n" +
        "</tr>\n" +
        "<tr>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>EPT15</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1500</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>200</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>540</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1150</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1950</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>190</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>64 Ач</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>85</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>4,2</strong></span></td>\n" +
        "</tr>\n" +
        "<tr>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>РТ15</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1500</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>200</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>540</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1150</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>2145</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>288</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>85</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>5,5</strong></span></td>\n" +
        "</tr>\n" +
        "<tr>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>РТ20</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>2000</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>200</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>540</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1150</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>2250</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>638</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>200</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>6,0</strong></span></td>\n" +
        "</tr>\n" +
        "<tr>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>LPT15</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1500</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>200</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>520</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1150</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1944</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>286</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>80</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "</tr>\n" +
        "<tr>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>LPT20</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>2000</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>200</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>540</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1150</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>2105/2144</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>520</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>210</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "</tr>\n" +
        "<tr>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>LPT22</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>2200</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>200</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>540</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1150</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>2105/2144</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>512</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>210</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "</tr>\n" +
        "<tr>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>CBD15W</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1500</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>520</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1150</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1708</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>230</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>80</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>5,3</strong></span></td>\n" +
        "</tr>\n" +
        "<tr>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>CWD20H</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>2000</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>120</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>520</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1150</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1895</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>500</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>165</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>5</strong></span></td>\n" +
        "</tr>\n" +
        "<tr>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>CBD20R-II</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>2000</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>202</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>520</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1150</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>1895</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>710</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>210</strong></span></td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\">&nbsp;</td>\n" +
        "<td style=\"font-size: 11px; margin: 8px; line-height: 1.42857; text-align: center; vertical-align: top; border: 1px dashed #bbbbbb; cursor: text; border-collapse: separate; border-spacing: 1px;\"><span style=\"font-size: 10pt;\"><strong>7</strong></span></td>\n" +
        "</tr>\n" +
        "</tbody>\n" +
        "</table>\n" +
        "<p>&nbsp;</p>\n" +
        "<p style=\"margin: 5px 0px 10px; padding: 0px; color: #555555;   font-size: 12.8px; line-height: 19.2px; text-align: justify;  \">Самоходная тележка или, как ее еще часто называют, &nbsp;электророхля – &nbsp;предназначена для транспортировки поддонов (палет). На большом складе, где необходимо преодолевать расстояния более 20 метров, она с успехом заменит ручную гидравлическую тележку.</p>\n" +
        "<p style=\"margin: 10px 0px; padding: 0px; color: #555555;   font-size: 12.8px; line-height: 19.2px; text-align: justify;  \">На нашем сайте вы можете заказать и купить электротележку марки NOBLIFT (Китай - США), полностью отвечающую мировым стандартам качества и безопасности. В обширном модельном ряду NOBLIFT непременно найдется электророхля с подходящими характеристиками.&nbsp;В наличии также транспортировщики паллет других достойных производителей (марку уточняйте у менеджера).&nbsp;</p>\t\t\t\t</div>\n" +
        "\t\t\t</div>\n" +
        "\t\t\t<div class=\"btp-detail-extrafields\">\n" +
        "\t\t\t\t\t\t\t</div>\n" +
        "\t\t</div>"
}